apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubegraph.fullname" . }}
  labels:
    {{- include "kubegraph.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kubegraph.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubegraph.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubegraph.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--cluster-name={{ .Values.kubernetes.clusterName }}"
          env:
            - name: KUBEGRAPH_CLUSTER_NAME
              value: {{ .Values.kubernetes.clusterName | quote }}
            {{- if .Values.neo4j.createSecret }}
            - name: NEO4J_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "kubegraph.fullname" . }}-neo4j
                  key: username
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "kubegraph.fullname" . }}-neo4j
                  key: password
            {{- else }}
            - name: NEO4J_USERNAME
              value: {{ .Values.neo4j.username | quote }}
            - name: NEO4J_PASSWORD
              value: {{ .Values.neo4j.password | quote }}
            {{- end }}
            - name: NEO4J_URI
              value: {{ .Values.neo4j.uri | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 
