{{- if .Values.neo4j.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubegraph.fullname" . }}-neo4j
  labels:
    {{- include "kubegraph.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.neo4j.username | b64enc }}
  password: {{ .Values.neo4j.password | b64enc }}
{{- end }} 
